type User {
    id: String!
    username: String!
}

type UserAndToken {
    user: User!
    token: String!
}

union CreateUserResponse = UserAndToken | GenericError
union LoginUserResponse = UserAndToken | GenericError
